apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quakewatch-chart.fullname" . }}
  labels:
    app: {{ include "quakewatch-chart.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "quakewatch-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "quakewatch-chart.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ include "quakewatch-chart.fullname" . }}-config
