replicaCount: 1

image:
  repository: nirreich84/quakewatch
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  create: true
  name: ""

service:
  type: LoadBalancer
  port: 80

containerPort: 5000

resources: {}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

config:
  DATABASE_HOST: mydb.example.com
  API_ENDPOINT: https://api.example.com/data
  OTHER_EXAMPLE: hello_world

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

