apiVersion: apps/v1
kind: Deployment
metadata:
  name: quakewatch-deployment
  labels:
    app: quakewatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quakewatch
  template:
    metadata:
      labels:
        app: quakewatch
    spec:
      containers:
      - name: quakewatch-container
        image: nirreich84/quakewatch:latest
        ports:
        - containerPort: 5000